# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f0205ca02ca783311417c318f1b90038a9b37e0d9cd13b98169b8e385d08e45a72981e12dbcbf3adba470445700991e78020b0f9f70923bb3bf6402c49b21b

test:
  secret_key_base: 00dd34d8e2e966adceaf95aac0b1fb7dfccb6daeb037b4db952d7002478fba8fb13a28802c7bfdf88b121b6191ed9757904a23188be6610c5b72289aaea934a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
